config/routes.rb
Rails.application.routes.draw do
  get '/host', to:'events#new'
  post'/host', to:'events#create'
  get 'events/show'
  get 'events_home', to:'events#index'
  get 'sessions/new'
  get    '/signup',   to: 'users#new'
  post   '/signup',   to: 'users#create'
  resources :users, only:['new','create','show']
  resources :events, only:['new','create','show']
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :creator, class_name: 'User', foreign_key: :user_id
  has_many :hosts, foreign_key: 'attended_event_id'
  has_many :attendees, through: :hosts

  # belongs_to :creator, foreign_key: :user_id, class_name:'User'
  # has_many :hosts,foreign_key:'attended_event_id'
  # has_many :attendees, through: :hosts

  scope :upcoming, -> { where(['date > ?', DateTime.now]) }
  scope :previous, -> { where(['date <= ?', DateTime.now]) }
end

app/models/host.rb
class Host < ApplicationRecord
  belongs_to :attended_event, class_name: 'Event'
  belongs_to :attendee, class_name: 'User'
end

app/models/user.rb
class User < ApplicationRecord
  has_many :created_events, foreign_key: 'user_id', class_name: 'Event'
  has_many :hosts, foreign_key: 'attendee_id'
  has_many :attended_events, through: :hosts

  # has_many :hosts, foreign_key:'attendee_id'
  # has_many :created_events,class_name:"Event"
  # has_many :attended_events, through: :hosts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include(SessionsHelper)
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def new; end

  def index
    @events = Event.all
  end

  def create
    @event = current_user.created_events.build(event_params)
    if @event.save
      redirect_to @event
    else
      render 'new'
    end
  end

  def show
    @event = Event.find(params[:id])
    @events = Event.all
  end

  private

  def event_params
    params.require(:event).permit(:date, :description)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new; end

  def create
    user = User.find_by(email: params[:session][:email])
    if user
      log_in(user)
      redirect_to(user)
    else
      render 'new'
    end
  end

  def destroy
    log_out
    redirect_to login_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(params.require(:user).permit(:name, :email))

    if @user.save
      redirect_to @user
    else
      render 'new'
    end
  end

  def show
    @user = User.find(params[:id])
    # Separate Past and Future Events
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !current_user.nil?
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/index.html.erb
<h2>Upcoming Events</h2>
  <ul>
      <% Event.upcoming.each do |date| %>
        <li>
          <%= date.description %>
        </li>  
      <% end %>
  </ul>

<h2>Past Events</h2>
  <ul>
      <% Event.previous.each do |date| %>
        <li>
          <%= date.description %>
        </li>  
      <% end %>
  </ul>

app/views/events/new.html.erb
<h1>Events#new</h1>
<br>
<%= form_for(:event,url: host_path) do |form| %>
  <%=form.label(:description)%>
  <br>
  <%=form.text_area(:description)%>
  <br>
  <%=form.label(:date)%>
  <br>
  <%=form.date_field(:date)%>
  <br>
  <%=form.submit%>
<%end%>

app/views/events/show.html.erb
<h3>Your Event </h3>
<br>
<%= @event.description %>
<br>
<h1>Attendees</h1>
<% @event.attendees.each do |event| %>
  <br>
  <hr>
  <%= event %>
<%end%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PrivateEvents</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <ul>
    <% if logged_in? %>
      <li><%= link_to "Create Event", host_path %></li>
      <li><%= link_to "Index", events_home_path %></li>
      <li><%= link_to "Log out", logout_path, method: :delete %></li>
    <% else %>
      <li><%= link_to "New User", signup_path %></li>
      <li><%= link_to "User Login", login_path %></li>
    <%end%>
  </ul>
    <%= yield %>
  </body>
</html>

app/views/users/new.html.erb
<h1>Users#new</h1>
  <br>
<%= form_for(@user) do |form| %>

  <%= form.label(:name)%>
  <%= form.text_field(:name)%>
  <br>
  <%= form.label(:email)%>
  <%= form.text_field(:email) %>
  <br>
  <%= form.submit %>
  <br>
<%end%>

app/views/users/show.html.erb
<h1>Users#show</h1>

<br>
<%= @user.email %>
<br>
<%= @user.name %>
<br>
<table>
  <tr>
    <td>
      <% if logged_in? %>
        Logged in as: <%= current_user.name %>
        <br>
        <h3>Events</h3>
        <br>
        <% @user.created_events.each do |event| %>
          <%= event.description %>
          <br>
          <hr>
        <%end%>
        <%else%>
          <br>
          <%= link_to "Login", login_path %>
      <%end%>
    </td>
    <td>
      <h1>User Attending Events</h1>
      <ul>
      <h2> Past Events </h2>
        <% @user.created_events.previous.each do |event| %>
          <li>
            <%= event.description %>
          </li>
        <%end%>
      <h2> Future Events </h2>
        <% @user.created_events.upcoming.each do |event| %>
        <li>
          <%= event.description %>
        </li>
        <%end%>
      </ul>
    </td>
  </tr>
</table>